### ISSUE TITLE
Unable to sign up with work account

### ISSUE THREAD

**Issue by DavidJFowler** [Azure-Samples/active-directory-external-identities-woodgrove-demo#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Click "Sign up with your work account"
Sign in on my organisation's sign in page

### Any log messages given by the failure
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'server_error', error_description: 'AADB2C90289: We encountered an error connecting to the identity provider. Please try again later.
Correlation ID: 63f8e242-6d6e-472a-8643-032c3a6cb318
Timestamp: 2019-10-02 14:51:03Z
', error_uri: 'error_uri is null'.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Expected/desired behavior
I am able to sign up to the application

### OS and Version?
> Windows 10, Google Chrome or IE 11

### Versions
>

### Mention any other details that might be useful

Logged in response to [https://github.com/MicrosoftDocs/azure-docs/issues/39955](https://github.com/MicrosoftDocs/azure-docs/issues/39955)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mmacy** [comment]
@adamstoffel What is the expected behavior for **Work Account** sign-up?

After some investigation, it seems we might need to be more clear about the expected behavior for work accounts in the text of the [overview article](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-overview#authenticate-business-customers). We say in the article that "...users are prompted to sign in with any Office 365 or Azure AD account," but I think the "any" in that sentence might need some qualification.

A quick test in an Incognito window yields a bit more informative error message that indicates a requirement that directories containing those work accounts must already be federated.

Either the article text needs updating, or we need better error handling/messaging in the app. Possibly both.

![image](https://user-images.githubusercontent.com/13394541/66578245-99edce80-eb2f-11e9-9c55-5d47608aad5e.png)
